# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."postgres-docker" = {
    image = "postgres:latest";
    environment = {
      "POSTGRES_PASSWORD" = "mypassword";
    };
    volumes = [
      "/home/luca/Nextcloud/Scripts/db-data/:/var/lib/postgresql/data:rw"
      "/home/luca/Nextcloud/Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:rw"
    ];
    ports = [
      "15432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=database"
      "--network=myproject_default"
    ];
  };
  systemd.services."docker-myproject-database" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-myproject_default.service"
    ];
    requires = [
      "docker-network-myproject_default.service"
    ];
    partOf = [
      "docker-compose-myproject-root.target"
    ];
    wantedBy = [
      "docker-compose-myproject-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-myproject_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f myproject_default";
    };
    script = ''
      docker network inspect myproject_default || docker network create myproject_default
    '';
    partOf = [ "docker-compose-myproject-root.target" ];
    wantedBy = [ "docker-compose-myproject-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-myproject-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
